Reorder description
jtr13/cc19 pull request #101
Opened 2019-10-29 23:52 UTC by Yingyu-Cao

2019-10-29 23:55 UTC, bojum commented
Won’t this create even more conflicts?

2019-10-30 00:01 UTC, Yingyu-Cao commented
No, I didn't change anything except for reordering them.

2019-10-30 00:05 UTC, skyetim requested changes

2019-10-30 00:05 UTC, skyetim commented on DESCRIPTION
> +  tidyverse,
Remove duplicate

2019-10-30 02:42 UTC, skyetim approved these changes

2019-11-07 02:54 UTC, skyetim commented
No longer applicable. Need to do it again after everything is merged.

2019-11-07 02:54 UTC, closed without merging