add cheatsheet for tidyverse
jtr13/cc19 pull request #104
Opened 2019-10-30 02:00 UTC by Huimin-alice

add a contributing file and a picture.

2019-11-04 13:51 UTC, RandomWalker300 requested changes
line 1: please add a space after hashtag
line6: please change your .png path to "resources/tidyverse_tutorial/tidyverseFinal.png"
please remove .DS_Store, and resources/.DS_Store

2019-11-04 13:51 UTC, RandomWalker300 commented on tidyverse_contribution.Rmd
> +#cheatsheet for tidyverse
1. line 1: add a space after hashtag
2. line6: change your .png path to "resources/tidyverse_tutorial/tidyverseFinal.png"
3. remove .DS_Store, and resources/.DS_Store

2019-11-06 02:18 UTC, Huimin-alice commented
all the problem listed as fixed, please check.

2019-11-06 02:21 UTC, Huimin-alice commented on tidyverse_contribution.Rmd
> +#cheatsheet for tidyverse
all problems listed are fixed, please check.

2019-11-07 14:15 UTC, merged

2019-11-07 14:15 UTC, skyetim commented
🎉 Congrats! Your contribution has been merged!