NFL Strategy Analysis - Swapnav Deka (sd3344)
jtr13/cc19 pull request #194
Opened 2019-12-19 21:59 UTC by sdeka1997

Request to merge my branch! Community Collaboration.

2019-12-22 09:54 UTC, skyetim requested changes

2019-12-22 09:54 UTC, skyetim commented on nfl_strat_analysis.Rmd
> +dcon <- dbConnect(SQLite(), dbname = "nfl.sqlite")
Error in match.names(clabs, names(xi)) : 
  names do not match previous names

Do you know why it raises error at this line?

2019-12-25 20:53 UTC, closed without merging

2019-12-25 20:53 UTC, sdeka1997 commented
CSV read problem.

2019-12-25 20:55 UTC, sdeka1997 commented
I did not use the Google Drive links for my original RMD, I used local
CSVs. I believe the problem was with the CSV read function from the Google
Drive. I have pushed a solution to my fork and created a new pull request:
https://github.com/jtr13/cc19/pull/195.
I closed the old pull request.

Best,


Swapnav Deka

M.S. in Data Science - Columbia University '20

B.A. in Statistics - Rice University '19

sdeka1997@gmail.com | (972) 375-2755 (cell)


On Sun, Dec 22, 2019 at 3:54 AM Tian Wang <notifications@github.com> wrote:

> *@skyetim* requested changes on this pull request.
> ------------------------------
>
> In nfl_strat_analysis.Rmd
> <https://github.com/jtr13/cc19/pull/194#discussion_r360694633>:
>
> > +library(knitr)
> +library(grid)
> +library(gridBase)
> +```
> +
> +```{r,include=FALSE,results='hide'}
> +NFL2010 <- read.csv("https://drive.google.com/open?id=1VCxo53CKGq1IMj2Pn2c7tel8F6pJSXtx")
> +NFL2011 <- read.csv("https://drive.google.com/open?id=1b3iXgSrxkpNcjOCm9ukWWFXsW5jwCUDW")
> +NFL2012 <- read.csv("https://drive.google.com/open?id=1vYpj25dLsoOow9DOrR4z8dBzwu4oNxNW")
> +NFL2013 <- read.csv("https://drive.google.com/open?id=1xjouqScJMqM5qBju1xM6R0JrD_rGb_yV")
> +teams <- read.csv("https://drive.google.com/open?id=1NzBXDkChZd41oBWnWo4PRGZlvETFtdbY")
> +weather_table <- read.csv(paste0("https://drive.google.com/open?id=1LkJzZ72RzwrER3NpYEr8DdncQHiE7730"))
> +merged <- read.csv("https://drive.google.com/open?id=1E0Ill7A_a3lHFBhgG0dAP4rQRCWb6g5Y")
> +
> +
> +dcon <- dbConnect(SQLite(), dbname = "nfl.sqlite")
>
> Error in match.names(clabs, names(xi)) :
> names do not match previous names
>
> Do you know why it raises error at this line?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jtr13/cc19/pull/194?email_source=notifications&email_token=ALM6VFMN7BNUKD2SVN5KLADQZ42MDA5CNFSM4J5RET32YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCQAXTTA#pullrequestreview-335641036>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALM6VFLIY2UZQQRT43BUGZDQZ42MDANCNFSM4J5RET3Q>
> .
>