files from Tinder study
jtr13/cc19 pull request #31
Opened 2019-10-27 04:16 UTC by bwliv

2019-10-27 18:43 UTC, bojum requested changes
Please remove tinder.html. See [1.3.5](https://jtr13.github.io/cc19/index.html#submission-steps)

2019-10-28 14:22 UTC, bwliv commented
thanks for taking care of this! doing it myself would have been complicated so i appreciate it

2019-10-28 19:27 UTC, bwliv commented
Did this work? Want to double check. Thanks!

2019-10-28 19:36 UTC, bojum commented
No problem! And thanks for checking. We are refactoring the way files are organized right now so don't worry about 'all checks have failed'.

2019-10-28 22:53 UTC, skyetim requested changes

2019-10-28 22:53 UTC, skyetim commented on tinder_study.Rmd
> +bentinder = devtools::install_github()
What’s the repo?

2019-10-28 22:54 UTC, bwliv commented
That can be removed. Fragment of unused code.

2019-10-28 23:06 UTC, skyetim commented
Please remove it as it causes the failure of building. I would suggest going through all the codes again to remove all redundant codes.

2019-10-28 23:09 UTC, bwliv commented
I deleted my local repo - can you just remove that line? It's the only necessary change I can see. Thanks!

2019-10-28 23:13 UTC, skyetim commented
Okay

2019-10-28 23:50 UTC, bojum commented
Remove the line causes a new error. `bentinder` object is not initialized before it is called in line 33. 
 Missing anything, @bwliv?

2019-10-29 00:05 UTC, bwliv commented
Yes, since bentinder is in .csv in resources I don't know where to read the data frame from - that I will need you to add. bentinder.csv should be in the resources. I can't do it because I don't know how bookdown loads resources. wasn't sure if it was the same as the normal command to load from the working directory. if so it just needs a bentinder = load.csv('bentinder.csv')

2019-10-29 00:41 UTC, bojum commented
🎉 merged!! Congrats and thank you for your contribution!!

2019-10-29 00:41 UTC, merged

2019-10-29 01:40 UTC, skyetim commented
all the photos are down. please change all the location like bentinder.csv