R - package writing workshop tutorial with link to the pdf
jtr13/cc19 pull request #37
Opened 2019-10-27 17:05 UTC by siddhantshandilya

2019-10-27 19:10 UTC, bojum commented on r-package-writing.Rmd
> +---
Remove this part

2019-10-27 19:11 UTC, bojum requested changes
- Remove the yml header.
- Put your workshop name at the top (see [here](https://jtr13.github.io/cc19/index.html#preparing-your-.rmd-file))

2019-10-28 23:37 UTC, siddhantshandilya commented
Made the required changes. Please merge! Thank you

2019-10-29 02:54 UTC, bojum commented
🎉 Merged! Thanks for your contribution!

2019-10-29 02:54 UTC, merged