File for Yuge Shen and Shengqing Xia
jtr13/cc19 pull request #60
Opened 2019-10-28 21:19 UTC by yuge97

2019-11-03 00:00 UTC, bl2788 commented on Multivariable_Regression_Tutorial.Rmd
> +```{r setup, include=FALSE}
because you have a setup trunk, please remove the setup label.

2019-11-03 00:03 UTC, bl2788 reviewed
1.please remove the setup label in your setup trunk
2.be aware that your png file's path may change when resources/<project_name>/ is created.

2019-11-03 00:03 UTC, bl2788 requested changes
1.remove the setup label in your setup trunk
2.be aware that your png file path may change when resources/<project_name>/ is created.

2019-11-03 01:31 UTC, bl2788 requested changes
You don't need to remove all the trunk, just remove the setup label itself.

2019-11-03 06:18 UTC, bl2788 requested changes
Sorry for the misunderstanding, it should be like {r , include=FALSE}

2019-11-03 12:45 UTC, bojum requested changes
@yuge97 Your content will look nicer if you remove one # from each of the # headers except for the first line. So that the rendered page wouldn't skip ##.

2019-11-08 21:03 UTC, merged

2019-11-08 21:03 UTC, bojum commented
🎉 Merged. Thanks for your contribution!