edav_info_heatmap_korean
jtr13/cc19 pull request #66
Opened 2019-10-28 22:38 UTC by juliajungahshin

edav_info_heatmap_korean

2019-11-03 02:25 UTC, st3186 requested changes
The Rmd file looks good except for the use of the named `setup` chunk, and maybe the use of numbered sections (which will be subject to change and will not update automatically if written this way).

Also, this should be merged into jtr13:master from your own new branch, not your own master.

2019-11-03 02:25 UTC, st3186 commented on edav_info_heatmap_korean.Rmd
> +```{r setup, include=FALSE}
this should read ```{r, include=FALSE}```.  There should be no "setup" tag in your submission

2019-11-03 02:25 UTC, st3186 commented on edav_info_heatmap_korean.Rmd
> +16.1 개요
Note that multiple hashtags like "## R Markdown" above will be rendered as sub-items (like, 4.1 R Markdown).  Given that, did you mean to write 16.1,2,3,etc.?  You may prefer to replace that with ## 개요, ## tl;dr, etc.

2019-11-07 03:59 UTC, st3186 commented
Hi! I started making some necessary changes to your branch before I realized that you're still trying to do a pull request from your master branch into jtr13:master.  The pull request actually cannot be master->master; can you add your .rmd file to a new branch and try to create a pull request from there?  Thanks!

2019-11-10 19:04 UTC, st3186 commented
Hi Julia, just checking I'm not sure that what you did worked.  Do you mind creating a brand new branch with just your .Rmd file and then trying to make pull request from that branch into jtr13:master? I think you closed and reopened this pull request but I'm not sure how to make it work without doing what I said above.  Sorry about that and thank you!

2019-11-12 17:08 UTC, skyetim commented
Duplicate of #171

2019-11-12 17:08 UTC, closed without merging