rmarkdown_tutorial
jtr13/cc19 pull request #78
Opened 2019-10-29 01:50 UTC by wsf375469088

2019-10-31 17:47 UTC, bojum commented
@skyetim @Yingyu-Cao, will line 121 in `rmarkdown_tutorial.Rmd` cause a problem?

2019-10-31 18:43 UTC, skyetim commented
> @skyetim @Yingyu-Cao, will line 121 in `rmarkdown_tutorial.Rmd` cause a problem?

Yes it will. I recommend taking a screenshot and put the screenshot instead.

2019-11-01 18:27 UTC, skyetim requested changes

2019-11-01 18:27 UTC, skyetim commented on rmarkdown_tutorial.Rmd
> +# Header1 {#anchor}
I recommend inserting a photo here. There should be no single # header other than the title.

2019-11-06 00:38 UTC, skyetim requested changes

2019-11-06 00:38 UTC, skyetim commented on rmarkdown_tutorial.Rmd
> +render("OutputExample.Rmd", output_format = "word_document")
this file doesn't exist.

2019-11-08 20:55 UTC, merged

2019-11-08 20:55 UTC, skyetim commented
🎉 Congrats! Your contribution has been merged!